trigger: 
 branches:
   include:
     - main
     - feature/*

pool:
  name: 24augpool

stages:
  - stage: terraformplanning
    displayName: Terraform Plan
    jobs:
      - job: terraformplan1
        displayName: Terraform Plan1
        steps:
          - task: TerraformInstaller@1
            displayName: Terraform install
            inputs:
              terraformVersion: latest

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'brijeshvipinsvc'
              backendAzureRmResourceGroupName: 'raman-rg'
              backendAzureRmStorageAccountName: 'stgforall'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: azurerm
              command: plan
              environmentServiceNameAzureRM: brijeshvipinsvc

  - stage: terraformapplypart
    displayName: terraform Apply
    jobs:
      - job: terraformapply
        displayName: Terraform Apply
        steps:
          - task: TerraformTask@5
            displayName: Terraform Apply
            inputs:
              provider: azurerm
              command: apply
              environmentServiceNameAzureRM: brijeshvipinsvc
    
