name: "shekhchilli"

on:
  push:
    branches:
      - main
      - 'feature/**'
      
jobs:
  build: 
    runs-on: shekhchilli
    steps: 
      - name: checkout code
        uses: actions/checkout@v5
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: latest
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan
        
        
