name: "shekhchilli"

on:
  push:
    branches:
      - main
      - 'feature/**'
      
jobs:
  build: 
    runs-on: shekchilli
    steps: 
      - name: checkout code
        uses: actions/checkout@v5
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: latest
      - name: terraform init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -no-color -out=plan.out

      - name: Show Terraform Plan Output
        run: terraform show -no-color plan.out
        
        
