name: "shekhchilli"

on:
  push:
    branches:
      - main
      - 'feature/**'
      
jobs:
  shekhchilli:
    name: terraform initwa
    runs-on: shekhchilli
    steps: 
      - name: terraform initwa1
        run: echo shekhchilli
        
